### PR TITLE
Add build files for ArchLinux

### PR DESCRIPTION
**Pull request by pharra**
it provides build config for Archlinux

### CODE REVIEW

**Comment by jakeday** [comment]
@pharra Can you update the readme information to not reference out to yours since it would be pulling from mine? Also, the script should reference the patches in my repo and not copies under the build directory. Lastly, use the rules from the root location and note that 99-ipts.rules is now 99-touchscreens.rules.

**Comment by jakeday** [comment]
@pharra Can we set a variable so the user can easily select which source version and patch set they want to use? And can we have the releases and build steps below the other ones for ubuntu?

We still need to change the source of the clone for the build step to use the linux-surface repo since it will be housed there now. Probably want to be more specific than calling the folder "build" as well, maybe "archbuild"?

Also, please don't leave commented out items in the readme.

After those changes, I think we'll be good! Thanks for putting this PR together!

**Comment by pharra** [comment]
@jakeday I have been changed the releases and archbuild position in readme, and I don't leave commented out items in the readme. Maybe I just don't notice that.
Also, I will try to set a variable which can select kernel version tomorrow.
Last, thank you for your great work on this work!

**Comment by Zyfarok** [comment]
Using git to download the linux-stable kernel is really slow, i would not recommend using this.
Also, you could probably automatically get arch config files from here : https://git.archlinux.org/svntogit/packages.git/tree/repos/core-x86_64?h=packages/linux
(Or use asp as explained here : https://wiki.archlinux.org/index.php/Kernels/Arch_Build_System )
It would probably be simpler and easier to update to a new version.

**Comment by Zyfarok** [comment]
Also, I tried to compile the 4.16 kernel from your repo and got this:
```
==> Starting prepare()...
choose kernel version which you want to build:
1) 4.14
2) 4.15
3) 4.16
#? 4.16
HEAD is now at 867ab4b2fcc3 Merge tag 'drm-fixes-for-v4.17-rc2' of git://people.freedesktop.org/~airlied/linux
error: pathspec 'linux-.y' did not match any file(s) known to git.
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by pharra** [comment]
@Zyfarok thanks for your suggestion. I'm sorry that it doesn' support input version number like 4.15.6 now.
You can input the number 1 or 2 or 3.

**Comment by Zyfarok** [comment]
Oh okay I'm stupid, I did not think about that.

**Comment by doofin** [comment]
I am an new arch user (manjaro),Are there problems with  Processor Microcode Firmware?

**Comment by tworzenieweb** [comment]
The current version is failing to compile. I am getting git pull error.

**Comment by martinnyborg** [comment]
I've gone ahead and created a new repo which contains the Arch package files. Instead being a part of the jakeday code, the package clones the necessary repos (linux-stable and linux-surface) and compiles the latest kernel. 

Link: https://github.com/martinnyborg/arch-surface-jakeday-kernel (Note: I have gotten the code to work, but I still have a lot of refactoring to do). 

I'm personally not a fan of mixing Arch build scripts with the code that it builds. 

Furthermore, I have removed the kernel version option and replaced it with hardcoded support for the latest kernel (4.17.3 as I type this) as Arch is a rolling release distro which strives to use the latest software.

**Comment by qzed** [comment]
@martinnyborg do you include the IPTS-firmware, WIFI-firmware, and patched libwacom? For me it would make more sense to separate them into their own packages. I've got some separate PKGBUILDs for libwacom and the IPTS firmware (Surface Book 2 only, could be easily adapted) laying around, if you want them.

**Comment by martinnyborg** [comment]
@qzed I do not, the package only build the kernel as I also believe that it makes more sense that they are separated (separation of concerns, plus the kernel is more frequently updated than the firmwares).

However step two is to make a package for those firmwares and tweaks, so it would be great if you would share your work! :)

**Comment by qzed** [comment]
Alright, I'll do a little cleanup and probably put them into a repo tomorrow, I'll keep you posted.

**Comment by qzed** [comment]
Done. They are available [here (firmware)](https://github.com/qzed/linux-firmware-ipts-surfacebook2-kbl8) and [here (libwacom)](https://github.com/qzed/libwacom-surface). I couldn't test them on my Surface Book 2 yet, as I have not gotten around to install Arch on it yet, so I could only test the build and installation process on my main machine. Feel free to open an issue if something is not working.

**Comment by martinnyborg** [comment]
@qzed Excellent, thank you!

**Comment by shieldwed** [comment]
Hi

I've been following this pull request for quite a while now as I am also an owner of a Surface Book 2 15". So far I have been creating the PKGBUILD and compiled the kernel myself (https://gitlab.com/aur-linux-surface/kernel). This work is based on the existing but not anymore updated AUR package https://aur.archlinux.org/packages/linux-surface4/.

Having been following this thread I am interested in joining efforts. My approach is basically to take the default kernel of Arch Linux and just add all relevant patches. Maybe we can compare the approaches and take out the best of each (@martinnyborg ?).

**Comment by martinnyborg** [comment]
@shieldwed Seems like we are doing exactly the same thing with the same general approach, so yeah lets work together :). 

My goal was to get the package on AUR (Maybe orphan the out-of-date package though I really hate the name linux-surface4), but whether we get mine or yours on AUR doesn't really matter to me. 

I have a bit more rewriting to do in my package (and a few bug reports to handle), so I'm going to finish that while taking a more in-depth look at your package setup.

**Comment by mirh** [comment]
In the grand scheme of things, having pre-built kernels somehow somewhere wouldn't hurt though (even though it's arch).

**Comment by LandKingdom** [comment]
Hello everyone, I've recently bought a Surface Pro 2017 and I tried compiling JakeDay's repo, but I couldn't get it to work. I'll try your changes now, and help where I can, since getting this on the AUR would help a lot of users, imo. Keep up the good work.

**Comment by jakeday** [comment]
Not applying at this time.

**Pull request closed without merging**
