### PR TITLE
Update surface-acpi, button patches and add support for Book 2 dGPU

### LINKED ISSUE #473: [Surface Laptop 2] System does not wake from suspend upon opening the lid
5.0.7-surface-linux-surface
Mint 19.1

My SL2 works great on this kernel, but I have to press the power button to wake it up. Minor inconvenience, but still annoying

### LINKED ISSUE #502: [Surface Laptop 2] Internal keyboard doesn't work.
Hi. Thank you for supporting this great hardware!
I just bought Surface Laptop 2 2018 and trying to get Linux work on it. At this point most hardware works fine but not internal keyboard.
I tried different versions of kernel but got the same problem.
Evtest shows both Microsoft Virtual HID Framework Device Keyboard and Microsoft Virtual HID Framework Device Consumer Control but there is no events comes from. I tried ACPI from this repo https://github.com/qzed/linux-surfacegen5-acpi but it change nothing.
Could you please help me to solve this problem. Thank you!

[    0.000000] Linux version 5.0.10-surface-linux-surface (jake@jake-Surface-Book-2) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10)) #5 SMP Wed May 1 06:29:54 EDT 2019
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.0.10-surface-linux-surface root=UUID=b059c592-0f21-4534-bf0f-3d5854f76465 ro quiet splash vt.handoff=1
[    0.107531] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.0.10-surface-linux-surface root=UUID=b059c592-0f21-4534-bf0f-3d5854f76465 ro quiet splash vt.handoff=1
[    1.554329] usb usb1: Manufacturer: Linux 5.0.10-surface-linux-surface xhci-hcd
[    1.556351] usb usb2: Manufacturer: Linux 5.0.10-surface-linux-surface xhci-hcd
[    4.455908] surfacegen5_acpi_san MSHW0091:00: Linked as a consumer to serial0-0
[    4.473696] surfacegen5_acpi_vhf MSHW0096:00: Linked as a consumer to serial0-0
[  546.069707] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  546.171513] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  546.273013] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  546.273032] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  546.374585] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  546.475077] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.075890] surfacegen5_acpi_ssh serial0-0: rqst: communication timed out
[  547.075908] surfacegen5_acpi_san MSHW0091:00: surfacegen5_ec_rqst: IO error occured, trying again
[  547.078952] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.078965] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.180686] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.282326] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.383695] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.484442] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  547.484460] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[  548.099775] surfacegen5_acpi_ssh serial0-0: rqst: communication timed out
[  548.099783] surfacegen5_acpi_san MSHW0091:00: surfacegen5_ec_rqst: IO error occured, trying again
[ 3028.026353] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message
[ 3028.127481] surfacegen5_acpi_ssh serial0-0: recv: invalid start of message

### PR DESCRIPTION
**Pull request by qzed**
Update surface-acpi patches to fix #502 and minor issues from kernel changes, update button patch to reflect changes from upstreaming process (edit: also fixes a spurious deferral issue that seems to occur on the latest kernel versions). 

Also adds in-kernel support for controlling the power-state of the dGPU on the Surface Book 2 by integrating https://github.com/qzed/linux-surfacebook2-mshw0153 (while it's still not quite done, it should be stable enough to include here).

Should also fix #473 by manually enabling GPE interrupts for the lid device.

### CODE REVIEW

**Comment by versipellis** [comment]
It'd be good to have some documentation in `setup.sh` for the dGPU power state module.

**Comment by qzed** [comment]
Right, we should consider a link or hint to some sort of documentation as this patch changes the default behavior of the dGPU (to off by default unless specified otherwise). A wiki entry for this would probably be helpful.

**Comment by TrustAugustus** [comment]
Hi qzed. I am thinking of importing your patches to the kernel /dsdt to MacOS. My technical skills are lacking but using voodooi2c with keyboard implementation is my goal. I'm willing to put a bounty of 100USD on the issue. If you are uninsterested, then its no problem. I appreciate you doing this for Linux. Its running great on my Surface Laptop 2. Cheers.

**Comment by MadcowD** [comment]
Is there a timeline on this being merged?

**Comment by qzed** [comment]
@MadcowD Since @jakeday seems a bit occupied at the moment I might build a `.deb` kernel package in the next couple of days and release it over at https://github.com/qzed/linux-surface. I'm not running a Debian based distro at the moment so I won't be able to test that though. I normally want to give Jake the last word on merging stuff in, so I'll be doing that over in my fork. I'll ping this issue when I've uploaded a release.

**Comment by qzed** [comment]
@MadcowD and anyone interested: I've uploaded a release: https://github.com/qzed/linux-surface/releases/tag/v5.2.5-pre1

**Comment by dsi3** [comment]
> @MadcowD and anyone interested: I've uploaded a release: https://github.com/qzed/linux-surface/releases/tag/v5.2.5-pre1

@qzed I installed Ubuntu 19.04 on my Surface Laptop 2 the other day, alongside your pre-release kernel version 5.2.5 (signed). It's the most stable Linux experience I've had so far on my device. In particular, touchpad tapping works great and doesn't die (not sure if this is 19.04 or the kernel). Suspend still shuts down the computer, unfortunately, and plugging in headphones causes the speakers to emit a humming noise. I also get a message on startup that says "error in communicating with TPM chip". The caps lock light hasn't fixed itself either. My machine's quite useable now though - thanks! :)

**Comment by qzed** [comment]
@dsi3 I think the TPM issue might be upstream thing, I've got the same message as soon as I switched to 5.2. As it doesn't seem break anything major it's pretty far down my list of things to fix at the moment though.

**Comment by runekaagaard** [comment]
@qzed Thanks for your heroic efforts! I took this release for a spin on a fresh install of Ubuntu 18.04.3 by first running the setup.sh script (without jakedays kernel) and then installing the deb packages from your release. I also got the following bugs:

- Speaker noise when headphones are attached
- Pen position is broken when screen is rotated.
- TPM communication error on boot
- Some times overheating when suspending by closing the lid, leading to an emergency shutdown. Other times works great.

The following works:

- Caps lock light.
- Touch position when screen is rotated
- Undocking/Docking

Generally it feels good.

Question: I can see at https://github.com/jakeday/linux-surface/blob/master/setup.sh#L181 that SKU Surface_Book_1793 (I assume thats the 15"?) uses an old version of ipts. What's the reason for that?

**Comment by qzed** [comment]
@runekaagaard Thanks for the praise!

I think the pen issue was reported some time ago on Gitter as bug in gnome. I experienced the same thing a while ago but now it works again, so I guess it's fixed and you just need to wait for an update.

Sadly, I still have no update on the suspend/overheating issue as I still haven't been able to reproduce this (apart from some issues when I suspend directly after resume, but they always looked different to the logs provided in #479). Could be that something wakes up the system, it notices that the lid is closed and tries to go back to sleep right away.

> Question: I can see at https://github.com/jakeday/linux-surface/blob/master/setup.sh#L181 that SKU Surface_Book_1793 (I assume thats the 15"?) uses an old version of ipts. What's the reason for that?

I honestly can't say if there's any reason for that. You should be able to use the latest firmware (or try to get it via Windows if you don't have it, I've written a bit about that in this readme https://github.com/qzed/linux-firmware-ipts-surfacebook2-kbl8#obtaining-the-firmware-files).

**Comment by runekaagaard** [comment]
@qzed Thanks for your prompt response.

About the overheating, I will dig into the logs and report what I can see over at #479. Will also try your latest system-sleep script from master and see if it makes a difference.

About the pen rotation, I noticed that the output of `libwacom-list-local-devices` is empty. I tried both copying `/usr/local/share/libwacom/surface.tablet` to `/usr/share/libwacom` and placing https://github.com/linuxwacom/libwacom/blob/a90e83e9e8822e97e40e85277597f744497b5b03/data/surface-book2-15.tablet in `/usr/share/libwacom`. Both makes it show on with `libwacom-list-local-devices` but it chrashes on boot with the error `event21 - ipts 045E:0020: tablet 'ipts 045E:0020' unknown to libwacom`.

**Comment by qzed** [comment]
@runekaagaard You definitely need the libwacom files for Gnome. The error indicates that libwacom does not find the data file for the tablet. You have installed the patched libwacom, right? That one doesn't just contain the data file but also changes to add the `mei` bus that is required for this to work. Without those changes, the data-file won't do anything. You can find the changes here: https://github.com/linuxwacom/libwacom/compare/master...qzed:ipts-mei

**Comment by runekaagaard** [comment]
@qzed Yes i installed the patched version of libwacom from setup.sh. But good news. I tried once more installing 19.04 and using _both_ your setup.sh and your kernel release. And...........

It works!!! <3 <3 <3

I've tested suspend repeatedly and i suspends to and from `s3idle` everytime without hickups so far. I suspended it overnight (about 10 hours) and it only lost form 10% to 3% battery. So.... great job!!!

The only remaining issue found so far was the rotation of the touchpad; pen rotation is fine. Maybe it's a path/compability issue with the inbuilt libwacom? `libwacom-list-local-devices` is still empty. I made a trivial workaround using dbus-monitor and xinput here: https://github.com/runekaagaard/linux-surfacebook2-rotation-bugfix.

Ahhhhh, cool hardware on greate software. Life is good :)

**Comment by woberts** [comment]
I also installed the qzed 5.2.5 release on a new 19.04 install on Surface Pro 2017. All seems stable as long as i turn off wifi before closing the surface cover. Sleep works ok and I can turn wifi back on when I wake the system by pressing the power key. If I leave wifi turned on, the system will wake OK, but wifi may not work without a reboot. Many thanks...

**Comment by versipellis** [comment]
@qzed Do you have a changelog for your prerelease build? Wondering if it solves some of the other issues I've been facing with suspend and dGPU.

**Comment by qzed** [comment]
@versipellis The change-log is mostly in the commit messages, for the 5.2 build these are the things that have changed compared to this PR:
- IPTS has been updated and re-worked a bit with regards to suspend/resume, it _should_ now work without unloading IPTS in the systemd-sleep script (which has been modified for that), but there still seem to be some issues (see #544), unfortunately I don't have the time to look into them at the moment. We've also added some debugging facilities to better solve the remaining problems.
- @kitakar5525 has added some updates to the NVME suspend patch for the SB1. As far as I know, those changes are already incorporated in 5.3.

Besides that there are the changes from this PR, i.e. mostly dGPU power state integration (just an integration of the [external module](https://github.com/qzed/linux-surfacebook2-mshw0153) into the kernel), minor fixes and changes in the button driver and some fixes in LID wakeup, although the latest fixes are not in the release yet. I'll probably try to update it this weekend.

The only times I had an issue with suspend (clipboard and/or base overheating) on the SB2 it was (I believe) some sort of suspend directly after resume, where the resume had not finished completely yet. I'm pretty sure I've got the dGPU-heating-up problem figured out, but I don't know how to fix it yet. Basically what I think happens is: Resume turns dGPU on (automatically via hardware/firmware even before the kernel kicks in, I think there's nothing I can do about that) and then when the device is suspended again _directly_ afterwards it thinks it is still suspended as it has never been officially resumed from the kernel, so the dGPU does not get turned off again. The rest is pretty standard behavior, when the dGPU is turned on, it gets warm. Not critically hot, but still cause for concern. This is behavior I've also experienced without using the dGPU power state module, however there it seems to turn off after some amount of time.

**Comment by qzed** [comment]
@woozysatsuma Yeah @versipellis is right, this looks definitely like missing GPU acceleration for video playback. Unfortunately that's a mixed bag on Linux. In some instances (browser, hardware, and video-codec combination) it works out of the box, in some cases it requires some settings to be changed, and in some other cases it unfortunately doesn't work at all. This all depends on a mixture of things, including support in the browser and kernel driver support, in our case that's the responsibility of the Intel iGPU via VA-API.

It's not something that's in the scope of this patch-set here, as this is not problem specific to Surface devices, pretty much any other device with an Intel CPU will have the exact same problems.

**Comment by kitakar5525** [comment]
The NVMe patch may also work for the other devices for better power management on suspend. I  picked needed patches from 5.3-rc.

**Comment by qzed** [comment]
@versipellis I don't have a guide yet. My plan was to eventually integrate this with vgaswitcheroo or bumblebee more directly so that manually enabling the dGPU and loading drivers would not be necessary any more.

At the moment, the following should do the trick (using the [surface-control](https://github.com/qzed/linux-surface-control) tool, you can also do this manually via sysfs and also control the initial power-state, see the [README](https://github.com/qzed/linux-surfacebook2-mshw0153/blob/master/README.md) for that):
1. Turn on the dGPU (`sudo surface dgpu set on`).
2. Load drivers (e.g. `sudo nvidia-modprobe`).
3. Use `optirun` (or alternatives) as usual.

To turn off, I strongly recommend unloading the drivers first, as this will fail if any application is still using the dGPU. You can keep the drivers loaded _as long as no application is actually using them_, but if that isn't the case you can expect crashes, so

4. Unload drivers (e.g. `sudo modprobe -r nvidia && sudo modprobe -r nvidia_drm`, potentially more)
5. If 4 succeeded, you can turn of the dGPU (`sudo surface dgpu set off`)

Thanks for reminding me of this, though! I've recently re-installed Linux and I've yet to install `optirun` again and make sure it works properly. It's been a while since I've set this up previously and I don't think `optirun` requires bumblebee (or some other kind of setup) but I might be mistaken. I'll try to remember that I should write down some instructions the next time I'm setting this up.

**Comment by qzed** [comment]
I'll close this PR for now, due to more updates and management in my fork. I'll send a new PR if it is requested.

**Pull request closed without merging**
